Update MoPubBrowser.java
Fix for another instance of

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
       at android.app.ContextImpl.startActivity(ContextImpl.java:847)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:276)
       at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:242)
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:330)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4429)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:3151)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:2918)
       at dalvik.system.NativeStart.main(NativeStart.java)